# Generated by Django 5.0 on 2024-11-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_waste"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanningStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("PLASTIC", "Plástico"),
                            ("PAPER", "Papel"),
                            ("GLASS", "Vidrio"),
                            ("ORGANIC", "Orgánico"),
                            ("METAL", "Metal"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bin_type",
                    models.CharField(
                        choices=[
                            ("GREEN", "Verde - Ordinarios"),
                            ("BLUE", "Azul - Plástico"),
                            ("GRAY", "Gris - Papel y Cartón"),
                            ("WHITE", "Blanco - Vidrio"),
                            ("BEIGE", "Beige - Orgánicos"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
