# Generated by Django 5.0 on 2024-11-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_scanningstatistics_co2_saved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanningstatistics",
            name="bin_type",
            field=models.CharField(
                choices=[
                    ("BLACK", "Black - Non-Recyclable"),
                    ("GREEN", "Green - Organic"),
                    ("WHITE", "White - Recyclable"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scanningstatistics",
            name="waste_type",
            field=models.CharField(
                choices=[
                    ("BOTTLE", "Bottle"),
                    ("PRINTED_PACKAGING", "Printed Packaging"),
                    ("CONTAINER", "Container"),
                    ("CAN", "Can"),
                    ("ORGANIC", "Organic"),
                    ("OTHER", "Others"),
                    ("NON_RECYCLABLE_PAPER", "Non-recyclable Paper"),
                    ("PAPERS", "Papers"),
                    ("UNCERTAIN", "Uncertain"),
                ],
                max_length=50,
            ),
        ),
    ]
