# Generated by Django 5.0 on 2024-11-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_scanningstatistics_bin_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanningstatistics",
            name="experience",
            field=models.IntegerField(default=0),
        ),
    ]
